(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const translations = {
    lt: {home:'Pradžia',heading:'Mokyklos turinio valdymas',logout:'Atsijungti',setupTitle:'Reikia paruošti turinio valdymą',setupText:'Prisijungimo paslauga dar nesukonfigūruota. Susisiekite su svetainės administratoriumi.',login:'Prisijungti',email:'El. paštas',password:'Slaptažodis',setPassword:'Nustatyti slaptažodį',newPassword:'Naujas slaptažodis (bent 8 simboliai)',savePassword:'Išsaugoti slaptažodį',news:'Naujienos',events:'Renginiai',photos:'Nuotraukos',access:'Prieiga',add:'Pridėti',editorEmail:'Redaktoriaus el. paštas',addEditor:'Pridėti redaktorių',accessHelp:'Pridėtas redaktorius gali iškart prisijungti šiuo el. paštu ir bendru PIN kodu.',editorLogin:'Redaktoriaus prisijungimas',ownerLogin:'Savininko prisijungimas',pin:'PIN kodas',pinHelp:'Prisijunkite patvirtintu el. paštu ir bendru redaktorių PIN kodu.',ownerHelp:'Savininkas prisijungia savo el. paštu ir asmeniniu slaptažodžiu.',empty:'Įrašų dar nėra.',edit:'Redaguoti',draft:'Juodraštis',published:'Paskelbta',slug:'Pavadinimas svetainės nuorodoje',date:'Data',dateLabelLT:'Rodoma data (LT, neprivaloma)',dateLabelEN:'Rodoma data (EN, neprivaloma)',titleLT:'Pavadinimas (LT)',titleEN:'Pavadinimas (EN)',summaryLT:'Santrauka (LT)',summaryEN:'Santrauka (EN)',bodyLT:'Tekstas (LT)',bodyEN:'Tekstas (EN)',plainText:'Rašykite paprastą tekstą. Pastraipas atskirkite nauja eilute.',photoURL:'Nuotraukos nuoroda',altLT:'Nuotraukos aprašymas (LT)',altEN:'Nuotraukos aprašymas (EN)',order:'Rikiavimo numeris',upload:'Įkelti nuotrauką',uploadHelp:'JPG, PNG arba WebP, iki 8 MB.',addPhoto:'Pridėti nuotrauką',removePhoto:'Pašalinti nuotrauką',preview:'Peržiūrėti',previewTitle:'Įrašo peržiūra',closePreview:'Uždaryti peržiūrą',saveDraft:'Išsaugoti juodraštį',publish:'Paskelbti',delete:'Ištrinti',cancel:'Atšaukti',deleteConfirm:'Ištrinti šį įrašą? Šio veiksmo atšaukti negalima.',revokeConfirm:'Atšaukti šio redaktoriaus prieigą?',revoke:'Atšaukti prieigą',owner:'Savininkas',editor:'Redaktorius',saving:'Išsaugoma…',saved:'Įrašas išsaugotas.',deleted:'Įrašas ištrintas.',uploaded:'Nuotrauka įkelta. Išsaugokite įrašą, kad ji būtų paskelbta.',editorAdded:'Redaktorius pridėtas.',revoked:'Prieiga atšaukta.',passwordSaved:'Slaptažodis išsaugotas.',loading:'Įkeliama…',noAccess:'Jūsų paskyrai nesuteikta redagavimo prieiga.',sessionExpired:'Sesija baigėsi. Prisijunkite dar kartą.',error:'Nepavyko atlikti veiksmo.',badUpload:'Pasirinkite JPG, PNG arba WebP failą iki 8 MB.',unsafeURL:'Nuotraukoms naudokite http arba https nuorodas.',working:'Atliekama…',status:'Būsena'},
    en: {home:'Home',heading:'School content editor',logout:'Sign out',setupTitle:'Content editor setup required',setupText:'The sign-in service is not configured yet. Please contact the website administrator.',login:'Sign in',email:'Email',password:'Password',setPassword:'Set your password',newPassword:'New password (at least 8 characters)',savePassword:'Save password',news:'News',events:'Events',photos:'Photos',access:'Access',add:'Add',editorEmail:'Editor email',addEditor:'Add editor',accessHelp:'An added editor can sign in immediately with this email and the shared PIN.',editorLogin:'Editor sign-in',ownerLogin:'Owner sign-in',pin:'PIN',pinHelp:'Sign in with your approved email and the shared editor PIN.',ownerHelp:'Owners sign in with their email and personal password.',empty:'No entries yet.',edit:'Edit',draft:'Draft',published:'Published',slug:'Name in the page URL',date:'Date',dateLabelLT:'Display date (LT, optional)',dateLabelEN:'Display date (EN, optional)',titleLT:'Title (LT)',titleEN:'Title (EN)',summaryLT:'Summary (LT)',summaryEN:'Summary (EN)',bodyLT:'Text (LT)',bodyEN:'Text (EN)',plainText:'Use plain text. Separate paragraphs with a new line.',photoURL:'Photo URL',altLT:'Photo description (LT)',altEN:'Photo description (EN)',order:'Display order',upload:'Upload photo',uploadHelp:'JPG, PNG or WebP, up to 8 MB.',addPhoto:'Add photo',removePhoto:'Remove photo',preview:'Preview',previewTitle:'Entry preview',closePreview:'Close preview',saveDraft:'Save draft',publish:'Publish',delete:'Delete',cancel:'Cancel',deleteConfirm:'Delete this entry? This cannot be undone.',revokeConfirm:'Revoke this editor’s access?',revoke:'Revoke access',owner:'Owner',editor:'Editor',saving:'Saving…',saved:'Entry saved.',deleted:'Entry deleted.',uploaded:'Photo uploaded. Save the entry to publish it.',editorAdded:'Editor added.',revoked:'Access revoked.',passwordSaved:'Password saved.',loading:'Loading…',noAccess:'Your account does not have editing access.',sessionExpired:'Your session expired. Please sign in again.',error:'The action could not be completed.',badUpload:'Choose a JPG, PNG or WebP file up to 8 MB.',unsafeURL:'Use http or https URLs for photos.',working:'Working…',status:'Status'}
  };
  let language = 'lt', config, session = null, user = null, role = null, activeTab = 'news', rows = [], refreshPromise = null;
  try { language = localStorage.getItem('genys-admin-language') || 'lt'; session = JSON.parse(localStorage.getItem('genys-admin-session') || 'null'); } catch {}
  if (!translations[language]) language = 'lt';
  const t = key => translations[language][key] || key;
  function node(tag, text, className) { const el = document.createElement(tag); if (text !== undefined) el.textContent = text; if (className) el.className = className; return el; }
  function labelText(el,key) { el.dataset.i18n=key; el.textContent=t(key); return el; }
  function translate() { document.documentElement.lang=language; document.querySelectorAll('[data-i18n]').forEach(el => el.textContent=t(el.dataset.i18n)); document.querySelectorAll('[data-language]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.language===language))); $('#list-heading').textContent=t(activeTab==='event'?'events':activeTab); }
  function message(value='',error=false) { $('#message').textContent=value; $('#message').classList.toggle('error',error); }
  function storeSession(value) { session=value; try { if(value) localStorage.setItem('genys-admin-session',JSON.stringify(value)); else localStorage.removeItem('genys-admin-session'); } catch {} }
  function adoptSession(data) { storeSession({...data,needsPassword:data.needsPassword ?? session?.needsPassword ?? false,expires_at:data.expires_at || Math.floor(Date.now()/1000)+(data.expires_in || 3600)}); }
  async function jsonResponse(response) { const text=await response.text(); let data; try{data=text?JSON.parse(text):null;}catch{data=null;} if(!response.ok) throw new Error(data?.error_description || data?.msg || data?.message || data?.error || t('error')); return data; }
  async function refresh() {
    if(refreshPromise) return refreshPromise;
    refreshPromise=(async()=>{if(!session?.refresh_token)throw new Error(t('sessionExpired')); const response=await fetch(config.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}); adoptSession(await jsonResponse(response));})().catch(error=>{signOut();throw error;}).finally(()=>{refreshPromise=null;});
    return refreshPromise;
  }
  async function api(path,options={},retry=true) {
    if(!session?.access_token) throw new Error(t('sessionExpired'));
    if(session.expires_at && session.expires_at < Date.now()/1000+60) await refresh();
    const headers={apikey:config.publishableKey,Authorization:'Bearer '+session.access_token,...options.headers};
    if(options.body && !(options.body instanceof Blob)) headers['Content-Type']='application/json';
    const response=await fetch(config.url+path,{...options,headers});
    if(response.status===401 && retry) {await refresh();return api(path,options,false);}
    return jsonResponse(response);
  }
  async function ownerAPI(method='GET',body,retry=true) { if(!session?.access_token)throw new Error(t('sessionExpired'));if(session.expires_at < Date.now()/1000+60) await refresh(); const response=await fetch('/api/content-editors',{method,headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}); if(response.status===401 && retry){await refresh();return ownerAPI(method,body,false);}return jsonResponse(response); }
  function signOut() {storeSession(null);user=null;role=null;rows=[];activeTab='news';selectLoginMode('editor');message();$('#items').replaceChildren();$('#editors').replaceChildren();$('#editor').replaceChildren();$('#access-panel').hidden=true;$('#content-panel').hidden=false;document.querySelectorAll('form').forEach(form=>form.reset());document.querySelectorAll('[data-tab]').forEach(tab=>tab.setAttribute('aria-pressed',String(tab.dataset.tab==='news')));$('#workspace').hidden=true;$('#password-panel').hidden=true;$('#logout').hidden=true;$('#login-panel').hidden=!config?.configured;$('#editor').hidden=true;}
  async function authorize(passwordNeeded=false,expectedRole=null) {
    passwordNeeded=passwordNeeded || Boolean(session?.needsPassword);
    user=await api('/auth/v1/user');
    const access=await api('/rest/v1/content_editors?user_id=eq.'+encodeURIComponent(user.id)+'&select=role');
    role=access?.[0]?.role;
    if(!['owner','editor'].includes(role) || (expectedRole && role!==expectedRole)) {signOut();throw new Error(t('noAccess'));}
    $('#login-panel').hidden=true;$('#logout').hidden=false;$('#password-panel').hidden=!passwordNeeded;$('#workspace').hidden=passwordNeeded;
    document.querySelector('[data-tab="access"]').hidden=role!=='owner';if(role!=='owner'&&activeTab==='access')activeTab='news';document.querySelectorAll('[data-tab]').forEach(tab=>tab.setAttribute('aria-pressed',String(tab.dataset.tab===activeTab)));
    if(!passwordNeeded) await loadItems();
  }
  function field(form,key,name,type='text',value='',required=false) { const label=node('label'); label.append(labelText(node('span'),key)); const input=node(type==='textarea'?'textarea':'input'); if(type!=='textarea') input.type=type; input.name=name;input.value=value??'';input.required=required;label.append(input);form.append(label);return input; }
  function button(key,callback,className='secondary') {const el=labelText(node('button',undefined,className),key);el.type='button';el.addEventListener('click',callback);return el;}
  function validPhotoURL(value) {if(!value)return '';try{const url=new URL(value,location.origin+'/');if(['http:','https:'].includes(url.protocol))return url.href;}catch{}throw new Error(t('unsafeURL'));}
  async function upload(file) {
    const extensions={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};
    if(!file || !extensions[file.type] || file.size>8*1024*1024 || file.size===0) throw new Error(t('badUpload'));
    const path=user.id+'/'+crypto.randomUUID()+'.'+extensions[file.type];
    await api('/storage/v1/object/site-photos/'+path,{method:'POST',headers:{'Content-Type':file.type,'x-upsert':'false'},body:file});
    return config.url+'/storage/v1/object/public/site-photos/'+path;
  }
  function photoFields(container,item={},removable=false) {
    const group=node('div',undefined,'image-row');let initialURL='';if(item.url){try{initialURL=validPhotoURL(item.url);}catch{initialURL=item.url;}}const url=field(group,'photoURL','url','url',initialURL);const fields=node('div',undefined,'fields');const altLT=field(fields,'altLT','alt_lt','text',item.alt_lt||'');const altEN=field(fields,'altEN','alt_en','text',item.alt_en||'');group.append(fields);
    const preview=node('img');preview.hidden=!item.url;if(item.url){try{preview.src=validPhotoURL(item.url);}catch{preview.hidden=true;}}preview.alt=item.alt_lt||'';group.append(preview);altLT.addEventListener('input',()=>preview.alt=altLT.value);url.addEventListener('change',()=>{try{preview.src=validPhotoURL(url.value);preview.hidden=!url.value;preview.alt=altLT.value;}catch(error){message(error.message,true);}});
    const uploadLabel=node('label');uploadLabel.append(labelText(node('span'),'upload'));const file=node('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';uploadLabel.append(file);group.append(uploadLabel,labelText(node('p',undefined,'help'),'uploadHelp'));
    file.addEventListener('change',()=>action(async()=>{file.disabled=true;try{url.value=await upload(file.files[0]);preview.src=url.value;preview.hidden=false;message(t('uploaded'));}finally{file.disabled=false;file.value='';}}));
    if(removable) group.append(button('removePhoto',()=>group.remove()));
    group.readPhoto=()=>({url:validPhotoURL(url.value),alt_lt:altLT.value.trim(),alt_en:altEN.value.trim()});container.append(group);return group;
  }
  function editItem(item={}) {
    const editor=$('#editor');editor.replaceChildren();editor.hidden=false;editor.append(labelText(node('h2'),item.id?'edit':'add'));
    const form=node('form');editor.append(form);const gallery=activeTab==='photos';
    if(!gallery){const slugInput=field(form,'slug','slug','text',item.slug||'',true);let slugEdited=Boolean(item.id||item.slug);slugInput.addEventListener('input',()=>slugEdited=true);slugInput.pattern='[a-z0-9]+(?:-[a-z0-9]+)*';const dates=node('div',undefined,'fields');field(dates,'date','date','date',item.date||'');field(dates,'dateLabelLT','date_label_lt','text',item.date_label_lt||'');field(dates,'dateLabelEN','date_label_en','text',item.date_label_en||'');form.append(dates);for(const pair of [['titleLT','title_lt','titleEN','title_en'],['summaryLT','summary_lt','summaryEN','summary_en'],['bodyLT','body_lt','bodyEN','body_en']]){const fields=node('div',undefined,'fields');field(fields,pair[0],pair[1],pair[1]==='title_lt'?'text':'textarea',item[pair[1]]||'',pair[1]==='title_lt');field(fields,pair[2],pair[3],pair[3]==='title_en'?'text':'textarea',item[pair[3]]||'',pair[3]==='title_en');form.append(fields);}form.append(labelText(node('p',undefined,'help'),'plainText'));form.elements.namedItem('title_lt').addEventListener('input',event=>{if(!slugEdited)slugInput.value=event.target.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');});}
    const images=node('div');form.append(images);if(gallery){photoFields(images,item);field(form,'order','sort_order','number',item.sort_order??0).step='1';}else{(Array.isArray(item.photos)?item.photos:[]).forEach(photo=>photoFields(images,photo,true));form.append(button('addPhoto',()=>photoFields(images,{},true)));}
    const actions=node('div',undefined,'actions');form.append(actions);const draft=labelText(node('button'),'saveDraft');draft.type='submit';draft.value='draft';const publish=labelText(node('button'),'publish');publish.type='submit';publish.value='published';actions.append(button('preview',()=>{try{const data=new FormData(form);const preview=node('section',undefined,'preview-panel');preview.tabIndex=-1;preview.setAttribute('aria-label',t('previewTitle'));preview.append(labelText(node('h2'),'previewTitle'));if(!gallery){preview.append(node('h3',data.get('title_'+language)||data.get('title_lt')||''),node('p',data.get('summary_'+language)||data.get('summary_lt')||''));String(data.get('body_'+language)||data.get('body_lt')||'').split(/\r?\n/).filter(paragraph=>paragraph.trim()).forEach(paragraph=>preview.append(node('p',paragraph)));}for(const group of images.children){const photo=group.readPhoto();if(photo.url){const image=node('img',undefined,'gallery-preview');image.src=photo.url;image.alt=photo['alt_'+language]||photo.alt_lt||'';preview.append(image);}}preview.append(button('closePreview',()=>preview.remove()));editor.querySelector('.preview-panel')?.remove();editor.append(preview);preview.focus();message();}catch(error){message(error.message,true);}}),draft,publish,button('cancel',()=>editor.hidden=true));
    if(item.id) actions.append(button('delete',()=>action(async()=>{if(!confirm(t('deleteConfirm')))return;await api('/rest/v1/'+(gallery?'content_photos':'content_posts')+'?id=eq.'+encodeURIComponent(item.id),{method:'DELETE'});editor.hidden=true;await loadItems();message(t('deleted'));}),'danger'));
    form.addEventListener('submit',event=>{event.preventDefault();const status=event.submitter?.value||'draft';action(async()=>{const data=new FormData(form);let payload={status};if(gallery){payload={...payload,...images.firstChild.readPhoto(),sort_order:Number(data.get('sort_order')||0)};if(!payload.url)throw new Error(t('photoURL'));}else{payload.kind=activeTab;for(const key of ['slug','title_lt','title_en','summary_lt','summary_en','body_lt','body_en','date_label_lt','date_label_en'])payload[key]=String(data.get(key)||'').trim();payload.date=data.get('date')||null;payload.photos=[...images.children].map(group=>group.readPhoto()).filter(photo=>photo.url);}
      const table=gallery?'content_photos':'content_posts';await api('/rest/v1/'+table+(item.id?'?id=eq.'+encodeURIComponent(item.id):''),{method:item.id?'PATCH':'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});editor.hidden=true;await loadItems();message(t('saved'));
    },form);});editor.scrollIntoView({behavior:'smooth',block:'nearest'});
  }
  async function loadItems() {
    translate();$('#editor').hidden=true;$('#access-panel').hidden=activeTab!=='access';$('#content-panel').hidden=activeTab==='access';
    if(activeTab==='access'){await loadEditors();return;}
    const gallery=activeTab==='photos';rows=await api('/rest/v1/'+(gallery?'content_photos?select=*&order=sort_order.asc,id.asc':'content_posts?select=*&kind=eq.'+activeTab+'&order=created_at.desc'));renderItems();
  }
  function renderItems() {const container=$('#items');container.replaceChildren();if(!rows.length){container.append(labelText(node('p'),'empty'));return;}rows.forEach(item=>{const row=node('div',undefined,'item');row.append(node('h3',activeTab==='photos'?(item['alt_'+language]||item.alt_lt||t('photos')):(item['title_'+language]||item.title_lt)));row.append(node('p',t(item.status)+(item.date?' · '+item.date:'')));if(activeTab==='photos'){try{const image=node('img',undefined,'gallery-preview');image.src=validPhotoURL(item.url);image.alt=item['alt_'+language]||item.alt_lt||'';image.loading='lazy';row.append(image);}catch{}}row.append(button('edit',()=>editItem(item)));container.append(row);});}
  async function loadEditors() {const container=$('#editors');container.replaceChildren();const members=await ownerAPI();members.forEach(member=>{const row=node('div',undefined,'access-row');row.append(node('span',(member.email||member.userId)+' · '+t(member.role)));if(member.role!=='owner' && member.userId!==user.id)row.append(button('revoke',()=>action(async()=>{if(!confirm(t('revokeConfirm')))return;await ownerAPI('DELETE',{userId:member.userId});await loadEditors();message(t('revoked'));}),'danger'));container.append(row);});}
  async function action(task,form) {const buttons=form?[...form.querySelectorAll('button')]:[];buttons.forEach(el=>el.disabled=true);message(t('working'));try{await task();}catch(error){message(error.message||t('error'),true);}finally{buttons.forEach(el=>el.disabled=false);}}
  document.querySelectorAll('[data-language]').forEach(el=>el.addEventListener('click',()=>{language=el.dataset.language;try{localStorage.setItem('genys-admin-language',language);}catch{}translate();if(rows.length&&activeTab!=='access')renderItems();}));
  document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>action(async()=>{activeTab=el.dataset.tab;document.querySelectorAll('[data-tab]').forEach(tab=>tab.setAttribute('aria-pressed',String(tab===el)));await loadItems();message();})));
  $('#logout').addEventListener('click',()=>action(async()=>{try{await api('/auth/v1/logout',{method:'POST'});}finally{signOut();}message();}));$('#add').addEventListener('click',()=>editItem());
  function selectLoginMode(mode) { $('#login-form').hidden=mode!=='editor';$('#owner-login-form').hidden=mode!=='owner';document.querySelectorAll('[data-login-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.loginMode===mode)));message(); }
  document.querySelectorAll('[data-login-mode]').forEach(button=>button.addEventListener('click',()=>selectLoginMode(button.dataset.loginMode)));
  $('#login-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const data=new FormData(event.target);const response=await fetch('/api/content-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),pin:data.get('pin')})});const result=await jsonResponse(response);adoptSession({...result,needsPassword:false});event.target.reset();await authorize(false,'editor');message();},event.target);});
  $('#owner-login-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{const data=new FormData(event.target);const response=await fetch(config.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),password:data.get('password')})});adoptSession({...await jsonResponse(response),needsPassword:false});event.target.reset();await authorize(false,'owner');message();},event.target);});
  $('#password-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{await api('/auth/v1/user',{method:'PUT',body:JSON.stringify({password:new FormData(event.target).get('password')})});storeSession({...session,needsPassword:false});event.target.reset();await authorize();message(t('passwordSaved'));},event.target);});
  $('#access-form').addEventListener('submit',event=>{event.preventDefault();action(async()=>{await ownerAPI('POST',{email:new FormData(event.target).get('email')});event.target.reset();await loadEditors();message(t('editorAdded'));},event.target);});
  async function start() {translate();message(t('loading'));try{const response=await fetch('/api/content-config');config=await jsonResponse(response);if(!config?.configured||!config.url||!config.publishableKey){$('#setup').hidden=false;message();return;}config.url=config.url.replace(/\/$/,'');const hash=new URLSearchParams(location.hash.slice(1));const invitation=hash.has('access_token');if(invitation){adoptSession({access_token:hash.get('access_token'),refresh_token:hash.get('refresh_token'),expires_in:Number(hash.get('expires_in'))||3600,needsPassword:true});history.replaceState(null,'',location.pathname+location.search);}if(session?.access_token){try{await authorize(invitation);message();}catch(error){signOut();message(error.message,true);}}else{$('#login-panel').hidden=false;message();}}catch(error){message(error.message,true);$('#setup').hidden=false;}}
  start();
})();
